import streamlit as st
import numpy as np
import plotly.graph_objects as go
from scipy.stats import norm

# --- THE MATH BRAINS ---

def mandelbrot(h, w, max_iter=20):
    """Generates the Mandelbrot set (The Beauty of Infinite Nature)"""
    y, x = np.ogrid[-1.4:1.4:h*1j, -2:0.8:w*1j]
    c = x + y*1j
    z = c
    divtime = max_iter + np.zeros(z.shape, dtype=int)
    for i in range(max_iter):
        z = z**2 + c
        diverge = z*np.conj(z) > 2**2
        div_now = diverge & (divtime == max_iter)
        divtime[div_now] = i
        z[diverge] = 2
    return divtime

def black_scholes_surface(S_range, T_range, K, r, sigma):
    """Generates a 3D surface of Option Prices (The Architecture of Risk)"""
    S, T = np.meshgrid(S_range, T_range)
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    price = (S * norm.cdf(d1)) - (K * np.exp(-r * T) * norm.cdf(d2))
    return S, T, price

# --- THE UI ---

st.set_page_config(page_title="Quantum Ledger", layout="wide")

st.title("🌌 The Quantum Ledger")
st.markdown("*A demonstration of how simple numbers create infinite complexity.*")

menu = st.sidebar.selectbox("Choose a Dimension", ["Fractal Nature", "Market Geometry", "About the Math"])

if menu == "Fractal Nature":
    st.header("1. The Mandelbrot Set: Order from Chaos")
    st.write("This fractal is generated by one simple rule: $z = z^2 + c$. It proves that infinite beauty is hidden in simple iteration.")
    
    iters = st.slider("Depth of Infinity (Iterations)", 10, 100, 30)
    fractal_data = mandelbrot(400, 400, max_iter=iters)
    
    fig = go.Figure(data=go.Heatmap(z=fractal_data, colorscale='Viridis'))
    fig.update_layout(width=800, height=800, xaxis_visible=False, yaxis_visible=False)
    st.plotly_chart(fig, use_container_width=True)

elif menu == "Market Geometry":
    st.header("2. The Black-Scholes Surface: The Shape of Risk")
    st.write("In finance, time and price create a 'surface' of probability. This is the math behind your wealth.")
    
    # Inputs
    K = st.sidebar.number_input("Strike Price", value=100)
    sigma = st.sidebar.slider("Volatility (σ)", 0.1, 1.0, 0.3)
    
    S_range = np.linspace(50, 150, 50)
    T_range = np.linspace(0.01, 1.0, 50)
    
    S, T, Z = black_scholes_surface(S_range, T_range, K, 0.05, sigma)
    
    fig = go.Figure(data=[go.Surface(z=Z, x=S, y=T, colorscale='Magma')])
    fig.update_layout(title='Option Price vs Stock Price & Time',
                      scene=dict(xaxis_title='Stock Price',
                                 yaxis_title='Time to Expiry',
                                 zaxis_title='Option Price'))
    st.plotly_chart(fig, use_container_width=True)

elif menu == "About the Math":
    st.info("Created for the 580-day grind. Math is the only truth that doesn't change.")